"""add model registry

Revision ID: 207041588ae7
Revises: d4a8e9910f41
Create Date: 2026-08-24 15:22:52.862960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207041588ae7'
down_revision: Union[str, Sequence[str], None] = 'd4a8e9910f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('base_model', sa.String(length=100), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('adapter_path', sa.Text(), nullable=True),
    sa.Column('training_job_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation.evaluation_id'], ),
    sa.ForeignKeyConstraint(['training_job_id'], ['training_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_registry_id'), 'model_registry', ['id'], unique=False)
    op.create_index(op.f('ix_model_registry_status'), 'model_registry', ['status'], unique=False)
    
    # Backfill default models for existing references in evaluation/pipeline_run tables
    op.execute(
        """
        INSERT INTO model_registry (id, model_name, version, base_model, status, created_at, updated_at)
        SELECT DISTINCT e.model_id, 'base_model_' || e.model_id, '1.0.0', 'base_model', 'CREATED', now(), now()
        FROM evaluation e
        WHERE e.model_id IS NOT NULL
        ON CONFLICT (id) DO NOTHING;
        """
    )
    op.execute(
        """
        SELECT setval(pg_get_serial_sequence('model_registry', 'id'), COALESCE((SELECT MAX(id) FROM model_registry), 1));
        """
    )

    op.create_foreign_key(None, 'evaluation', 'model_registry', ['model_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('pipeline_run_dataset_id_fkey'), 'pipeline_run', type_='foreignkey')
    op.drop_constraint(op.f('pipeline_run_dataset_version_id_fkey'), 'pipeline_run', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_run', 'dataset_version', ['dataset_version_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pipeline_run', 'model_registry', ['model_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pipeline_run', 'dataset', ['dataset_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipeline_run', type_='foreignkey')
    op.drop_constraint(None, 'pipeline_run', type_='foreignkey')
    op.drop_constraint(None, 'pipeline_run', type_='foreignkey')
    op.create_foreign_key(op.f('pipeline_run_dataset_version_id_fkey'), 'pipeline_run', 'dataset_version', ['dataset_version_id'], ['id'])
    op.create_foreign_key(op.f('pipeline_run_dataset_id_fkey'), 'pipeline_run', 'dataset', ['dataset_id'], ['id'])
    op.drop_constraint(None, 'evaluation', type_='foreignkey')
    op.drop_index(op.f('ix_model_registry_status'), table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_id'), table_name='model_registry')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
