"""allow null worker id

Revision ID: becedf322d72
Revises: c47441409e2b
Create Date: 2026-08-22 21:39:28.211532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'becedf322d72'
down_revision: Union[str, Sequence[str], None] = 'c47441409e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_job', 'worker_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_job', 'worker_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
