//=======================================================================================//
/*
AI Playground: Interactive inference sandbox evaluating active deployed enterprise models.
*/
//=======================================================================================//
"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { Loader2, Bot, AlertCircle } from "lucide-react";
import PlaygroundParametersPanel, {
  SYSTEM_ROLE_PRESETS,
} from "@/components/playground/PlaygroundParametersPanel";
import PlaygroundChatWindow from "@/components/playground/PlaygroundChatWindow";
import { getDeployments } from "@/app/services/deploymentService/deploymentServices";
import { getModels } from "@/app/services/modelService/modelServices";
import { runInference } from "@/app/services/inferenceService/inferenceServices";
import { toast } from "sonner";

export default function PlaygroundPage() {
  const [deployedModels, setDeployedModels] = useState([]);
  const [selectedModelId, setSelectedModelId] = useState("");
  const [loadingModels, setLoadingModels] = useState(true);
  const [inferencing, setInferencing] = useState(false);
  const inferencingRef = useRef(false);

  const [parameters, setParameters] = useState({
    temperature: 0.2,
    topP: 0.9,
    maxTokens: 256,
    taskType: SYSTEM_ROLE_PRESETS[0].taskType || "sft_grounded_generation",
    systemInstruction: SYSTEM_ROLE_PRESETS[0].instruction,
  });

  // Start with empty chat — the playground shows real inference results only
  const [messages, setMessages] = useState([]);
  const [tokenCount, setTokenCount] = useState(0);

  // Fetch only active deployed models
  const fetchDeployedModels = useCallback(async () => {
    try {
      setLoadingModels(true);
      const deploymentsData = await getDeployments().catch(() => []);

      const activeDeployments = Array.isArray(deploymentsData)
        ? deploymentsData.filter((d) => (d.status || "").toUpperCase() === "ACTIVE")
        : [];

      // Deduplicate by model_id to keep latest active deployment per model
      const uniqueByModel = [];
      const seenModels = new Set();
      for (const d of activeDeployments) {
        if (!seenModels.has(d.model_id)) {
          seenModels.add(d.model_id);
          uniqueByModel.push(d);
        }
      }

      setDeployedModels(uniqueByModel);
      if (uniqueByModel.length > 0) {
        setSelectedModelId(String(uniqueByModel[0].model_id));
      } else {
        setSelectedModelId("");
      }
    } catch (err) {
      console.error("Failed to load deployed models:", err);
      toast.error("Failed to load deployed models");
    } finally {
      setLoadingModels(false);
    }
  }, []);

  useEffect(() => {
    fetchDeployedModels();
  }, [fetchDeployedModels]);

  const activeModel = deployedModels.find(
    (m) => String(m.model_id) === String(selectedModelId)
  ) || deployedModels[0];

  // Send message to inference API with single submission lock ownership
  const handleSendMessage = async (userPrompt) => {
    if (!selectedModelId) {
      toast.error("Please select a deployed model first");
      return;
    }

    // Synchronous submission lock check to prevent duplicate concurrent submissions
    if (inferencingRef.current) return;
    inferencingRef.current = true;
    setInferencing(true);

    const newMessages = [...messages, { role: "user", content: userPrompt }];
    setMessages(newMessages);

    try {
      const validTaskType = parameters.taskType || "customer_faq_qa";
      const result = await runInference({
        model_id: parseInt(selectedModelId, 10),
        task_type: validTaskType,
        question: userPrompt,
        context: parameters.systemInstruction?.toLowerCase().startsWith("you are") ? "" : parameters.systemInstruction,
        max_new_tokens: parameters.maxTokens,
        temperature: parameters.temperature,
        top_p: parameters.topP,
        do_sample: false,
      });

      let assistantText = "";
      if (typeof result?.response === "string" && result.response.trim()) {
        assistantText = result.response.trim();
      } else if (typeof result?.response === "object" && result.response !== null) {
        assistantText = JSON.stringify(result.response, null, 2);
      } else if (typeof result?.raw_response === "string" && result.raw_response.trim()) {
        assistantText = result.raw_response.trim();
      } else if (result?.text) {
        assistantText = result.text;
      } else {
        assistantText = "No response generated by model.";
      }

      setMessages([
        ...newMessages,
        {
          role: "assistant",
          content: assistantText,
          latency: result?.latency_seconds,
          tokens: result?.tokens_generated,
          model_name: result?.model_name || activeModel?.model_name,
          dataset_name: result?.dataset_name || activeModel?.dataset_name,
          dataset_version: result?.dataset_version || activeModel?.dataset_version,
          dataset_file_name: result?.dataset_file_name || activeModel?.dataset_file_name,
          training_run_id: result?.training_run_id || activeModel?.training_run_id,
        },
      ]);
      // Update token count from real API response
      if (result?.tokens_generated != null) {
        setTokenCount((prev) => prev + (result.tokens_generated || 0));
      }
    } catch (err) {
      console.error("Inference failed:", err);
      const status = err?.response?.status;
      const serverDetail = err?.response?.data?.detail;

      let errorMsg = "Unable to generate a response due to a server error.";
      let toastTitle = "Inference Failed";

      if (status === 429) {
        toastTitle = "Server Busy (Rate Limited)";
        errorMsg = "The inference service is temporarily busy. Please try again in a few seconds.";
      } else if (status === 400 || status === 422) {
        toastTitle = "Invalid Request";
        if (typeof serverDetail === "string" && serverDetail.toLowerCase().includes("task type")) {
          errorMsg = "The selected task type is not supported.";
        } else if (typeof serverDetail === "string") {
          errorMsg = serverDetail;
        } else {
          errorMsg = "The request parameters are invalid.";
        }
      } else if (status === 503) {
        toastTitle = "Service Unavailable";
        errorMsg = "The model service is currently unavailable. Please try again shortly.";
      } else if (status === 504) {
        toastTitle = "Gateway Timeout";
        errorMsg = "Inference request timed out. The model may still be initializing.";
      } else if (typeof serverDetail === "string" && serverDetail.trim() && serverDetail.length < 200) {
        errorMsg = serverDetail;
      }

      toast.error(toastTitle, {
        description: errorMsg,
      });

      setMessages([
        ...newMessages,
        {
          role: "assistant",
          content: `⚠️ Failed to generate response: ${errorMsg}`,
        },
      ]);
    } finally {
      inferencingRef.current = false;
      setInferencing(false);
    }
  };

  const handleClearChat = () => {
    setMessages([]);
    setTokenCount(0);
    toast.success("Chat history cleared");
  };

  const handleResetParameters = () => {
    setParameters({
      temperature: 0.2,
      topP: 0.9,
      maxTokens: 256,
      taskType: SYSTEM_ROLE_PRESETS[0].taskType || "sft_grounded_generation",
      systemInstruction: SYSTEM_ROLE_PRESETS[0].instruction,
    });
    toast.success("Parameters reset to default");
  };

  if (loadingModels) {
    return (
      <main className="flex min-h-[70vh] items-center justify-center lg:ml-[280px]">
        <div className="flex flex-col items-center gap-3">
          <Loader2 className="h-8 w-8 animate-spin text-[#002B55]" />
          <p className="text-gray-600 text-sm font-medium">
            Loading deployed models. Please wait...
          </p>
        </div>
      </main>
    );
  }

  return (
    <main className="flex flex-col mt-10 pt-10 lg:pt-15 px-2 lg:px-8 lg:ml-[280px] pb-8 h-[calc(100vh-40px)]">
      {/* Page Title / Subtitle */}
      <div className="mb-4 px-3 lg:px-0">
        <h1 className="text-2xl lg:text-3xl font-extrabold text-gray-900 tracking-tight">
          AI Playground
        </h1>
        <p className="text-xs lg:text-sm text-gray-500 mt-0.5 font-medium">
          Interactive inference sandbox evaluating active deployed enterprise models.
        </p>
      </div>

      {/* 2-Column Playground Grid matching Screenshot */}
      <div className="grid grid-cols-1 lg:grid-cols-[1fr_360px] gap-6 flex-1 min-h-0">
        {/* Left: Chat Window */}
        <div className="h-full min-h-[500px]">
          <PlaygroundChatWindow
            activeModel={activeModel}
            messages={messages}
            onSendMessage={handleSendMessage}
            onClearChat={handleClearChat}
            loading={inferencing}
            tokenCount={tokenCount}
          />
        </div>

        {/* Right: Parameters Panel */}
        <div className="h-full min-h-[500px]">
          <PlaygroundParametersPanel
            deployedModels={deployedModels}
            selectedModelId={selectedModelId}
            activeModel={activeModel}
            onModelChange={(id) => setSelectedModelId(id)}
            parameters={parameters}
            onParametersChange={(newParams) => setParameters(newParams)}
            onReset={handleResetParameters}
          />
        </div>
      </div>
    </main>
  );
}
